export const ADD_BOOK="ADD_BOOK";
export const UPDATE_BOOK="UPDATE_BOOK";
export const DELETE_BOOK="DETELE_BOOK";
export const CHERCHER_BOOK="CHERCHER_BOOK";

export const ADD_USER="ADD_USER";
export const UPDATE_USER="UPDATE_USER";
export const DELETE_USER="DETELE_USER";
export const CHERCHER_USER="CHERCHER_USER";


export const ADD_COMMANDE="ADD_COMMANDE";
export const UPDATE_COMMANDE="UPDATE_COMMANDE";
export const DELETE_COMMANDE="DETELE_COMMANDE";


export const FILTRER="FILTRER";
export const CHERCHER_PAR_TITRE="CHERCHER_PAR_TITRE";


export const ADD_FAVORIS="ADD_FAVORIS";
export const DELETE_FAVORIS="DELETE_FAVORIS";